name: CI / Client

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
    paths:
      - '*.json'
      - '@types/**'
      - 'svelte.config.js'
      - 'src/**'
  pull_request:
    tags-ignore:
      - '**'
    branches:
      - 'master'
    paths:
      - '*.json'
      - '@types/**'
      - 'svelte.config.js'
      - 'src/**'

jobs:
  test:
    name: Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: (setup) pnpm
      run: npm install -g pnpm

    - name: Install
      run: pnpm install --frozen-lockfile

    - name: Builds
      run: yarn svelte-kit build
